ervices:
  - type: web
    name: digquest
    env: node
    plan: starter
    repo: https://github.com/DigQuestor/digquest
    branch: main
    rootDir: .
    buildCommand: |
      echo "=== RENDER BUILD DEBUG ==="
      pwd && ls -la
      npm install --production=false --verbose
      npx vite build --config vite.config.minimal.ts --mode production
      npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist --target=node18
      echo "=== BUILD COMPLETE ==="
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: digquest-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
databases:
  - name: digquest-db
    databaseName: digquest
    user: digquest_user
    plan: starter
