services:
  - type: web
    name: digquest-final
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: digquest-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
databases:
  - name: digquest-db
    databaseName: digquest
    user: digquest_user
    plan: starter
