services:
  - type: web
    name: digquest
    env: node
    plan: starter
    buildCommand: |
      echo "=== RENDER BUILD DEBUG ==="
      echo "Working directory: $(pwd)"
      echo "Directory contents:"
      ls -la
      echo "=== INSTALLING DEPENDENCIES ==="
      npm install --production=false
      echo "=== BUILDING CLIENT ==="
      npx vite build --config vite.config.minimal.ts
      echo "=== BUILDING SERVER ==="
      npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
      echo "=== BUILD COMPLETE ==="
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: digquest-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
databases:
  - name: digquest-db
    databaseName: digquest
    user: digquest_user
    plan: starter
