services:
  - type: web
    name: digquest-v2
    env: node
    plan: starter
    buildCommand: npm install && vite build --config vite.production.config.ts && esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: VITE_GOOGLE_MAPS_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: digquest-db
    databaseName: digquest
    user: digquest_user
    plan: starter