services:
  - type: web
    name: digquest
    env: node
    plan: starter
    buildCommand: echo "Working in $(pwd)" && ls -la && npm install --production=false && npx vite build --config vite.config.minimal.ts && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: digquest-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
databases:
  - name: digquest-db
    databaseName: digquest
    user: digquest_user
    plan: starter
